spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: usr_postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false